server:
  port: 11083

spring:
  profiles:
    active: ss

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password:

  #配置redis连接信息(单机模式)
  redis:
    host: 127.0.0.1
    port: 6379
    password: